// <auto-generated />
using System;
using AdessoRideShare.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdessoRideShare.Database.Migrations
{
    [DbContext(typeof(RideShareDbContext))]
    [Migration("20200208121655_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdessoRideShare.Database.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("XCoord")
                        .HasColumnType("int");

                    b.Property<int>("YCoord")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            XCoord = 0,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 2,
                            XCoord = 50,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 3,
                            XCoord = 100,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 4,
                            XCoord = 150,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 5,
                            XCoord = 200,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 6,
                            XCoord = 250,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 7,
                            XCoord = 300,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 8,
                            XCoord = 350,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 9,
                            XCoord = 400,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 10,
                            XCoord = 450,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 11,
                            XCoord = 500,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 12,
                            XCoord = 550,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 13,
                            XCoord = 600,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 14,
                            XCoord = 650,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 15,
                            XCoord = 700,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 16,
                            XCoord = 750,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 17,
                            XCoord = 800,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 18,
                            XCoord = 850,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 19,
                            XCoord = 900,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 20,
                            XCoord = 950,
                            YCoord = 0
                        },
                        new
                        {
                            CityId = 21,
                            XCoord = 0,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 22,
                            XCoord = 50,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 23,
                            XCoord = 100,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 24,
                            XCoord = 150,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 25,
                            XCoord = 200,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 26,
                            XCoord = 250,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 27,
                            XCoord = 300,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 28,
                            XCoord = 350,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 29,
                            XCoord = 400,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 30,
                            XCoord = 450,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 31,
                            XCoord = 500,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 32,
                            XCoord = 550,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 33,
                            XCoord = 600,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 34,
                            XCoord = 650,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 35,
                            XCoord = 700,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 36,
                            XCoord = 750,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 37,
                            XCoord = 800,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 38,
                            XCoord = 850,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 39,
                            XCoord = 900,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 40,
                            XCoord = 950,
                            YCoord = 50
                        },
                        new
                        {
                            CityId = 41,
                            XCoord = 0,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 42,
                            XCoord = 50,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 43,
                            XCoord = 100,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 44,
                            XCoord = 150,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 45,
                            XCoord = 200,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 46,
                            XCoord = 250,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 47,
                            XCoord = 300,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 48,
                            XCoord = 350,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 49,
                            XCoord = 400,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 50,
                            XCoord = 450,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 51,
                            XCoord = 500,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 52,
                            XCoord = 550,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 53,
                            XCoord = 600,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 54,
                            XCoord = 650,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 55,
                            XCoord = 700,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 56,
                            XCoord = 750,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 57,
                            XCoord = 800,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 58,
                            XCoord = 850,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 59,
                            XCoord = 900,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 60,
                            XCoord = 950,
                            YCoord = 100
                        },
                        new
                        {
                            CityId = 61,
                            XCoord = 0,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 62,
                            XCoord = 50,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 63,
                            XCoord = 100,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 64,
                            XCoord = 150,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 65,
                            XCoord = 200,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 66,
                            XCoord = 250,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 67,
                            XCoord = 300,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 68,
                            XCoord = 350,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 69,
                            XCoord = 400,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 70,
                            XCoord = 450,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 71,
                            XCoord = 500,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 72,
                            XCoord = 550,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 73,
                            XCoord = 600,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 74,
                            XCoord = 650,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 75,
                            XCoord = 700,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 76,
                            XCoord = 750,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 77,
                            XCoord = 800,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 78,
                            XCoord = 850,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 79,
                            XCoord = 900,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 80,
                            XCoord = 950,
                            YCoord = 150
                        },
                        new
                        {
                            CityId = 81,
                            XCoord = 0,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 82,
                            XCoord = 50,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 83,
                            XCoord = 100,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 84,
                            XCoord = 150,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 85,
                            XCoord = 200,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 86,
                            XCoord = 250,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 87,
                            XCoord = 300,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 88,
                            XCoord = 350,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 89,
                            XCoord = 400,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 90,
                            XCoord = 450,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 91,
                            XCoord = 500,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 92,
                            XCoord = 550,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 93,
                            XCoord = 600,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 94,
                            XCoord = 650,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 95,
                            XCoord = 700,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 96,
                            XCoord = 750,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 97,
                            XCoord = 800,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 98,
                            XCoord = 850,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 99,
                            XCoord = 900,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 100,
                            XCoord = 950,
                            YCoord = 200
                        },
                        new
                        {
                            CityId = 101,
                            XCoord = 0,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 102,
                            XCoord = 50,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 103,
                            XCoord = 100,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 104,
                            XCoord = 150,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 105,
                            XCoord = 200,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 106,
                            XCoord = 250,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 107,
                            XCoord = 300,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 108,
                            XCoord = 350,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 109,
                            XCoord = 400,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 110,
                            XCoord = 450,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 111,
                            XCoord = 500,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 112,
                            XCoord = 550,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 113,
                            XCoord = 600,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 114,
                            XCoord = 650,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 115,
                            XCoord = 700,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 116,
                            XCoord = 750,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 117,
                            XCoord = 800,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 118,
                            XCoord = 850,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 119,
                            XCoord = 900,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 120,
                            XCoord = 950,
                            YCoord = 250
                        },
                        new
                        {
                            CityId = 121,
                            XCoord = 0,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 122,
                            XCoord = 50,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 123,
                            XCoord = 100,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 124,
                            XCoord = 150,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 125,
                            XCoord = 200,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 126,
                            XCoord = 250,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 127,
                            XCoord = 300,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 128,
                            XCoord = 350,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 129,
                            XCoord = 400,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 130,
                            XCoord = 450,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 131,
                            XCoord = 500,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 132,
                            XCoord = 550,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 133,
                            XCoord = 600,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 134,
                            XCoord = 650,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 135,
                            XCoord = 700,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 136,
                            XCoord = 750,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 137,
                            XCoord = 800,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 138,
                            XCoord = 850,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 139,
                            XCoord = 900,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 140,
                            XCoord = 950,
                            YCoord = 300
                        },
                        new
                        {
                            CityId = 141,
                            XCoord = 0,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 142,
                            XCoord = 50,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 143,
                            XCoord = 100,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 144,
                            XCoord = 150,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 145,
                            XCoord = 200,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 146,
                            XCoord = 250,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 147,
                            XCoord = 300,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 148,
                            XCoord = 350,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 149,
                            XCoord = 400,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 150,
                            XCoord = 450,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 151,
                            XCoord = 500,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 152,
                            XCoord = 550,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 153,
                            XCoord = 600,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 154,
                            XCoord = 650,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 155,
                            XCoord = 700,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 156,
                            XCoord = 750,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 157,
                            XCoord = 800,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 158,
                            XCoord = 850,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 159,
                            XCoord = 900,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 160,
                            XCoord = 950,
                            YCoord = 350
                        },
                        new
                        {
                            CityId = 161,
                            XCoord = 0,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 162,
                            XCoord = 50,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 163,
                            XCoord = 100,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 164,
                            XCoord = 150,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 165,
                            XCoord = 200,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 166,
                            XCoord = 250,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 167,
                            XCoord = 300,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 168,
                            XCoord = 350,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 169,
                            XCoord = 400,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 170,
                            XCoord = 450,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 171,
                            XCoord = 500,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 172,
                            XCoord = 550,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 173,
                            XCoord = 600,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 174,
                            XCoord = 650,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 175,
                            XCoord = 700,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 176,
                            XCoord = 750,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 177,
                            XCoord = 800,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 178,
                            XCoord = 850,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 179,
                            XCoord = 900,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 180,
                            XCoord = 950,
                            YCoord = 400
                        },
                        new
                        {
                            CityId = 181,
                            XCoord = 0,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 182,
                            XCoord = 50,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 183,
                            XCoord = 100,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 184,
                            XCoord = 150,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 185,
                            XCoord = 200,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 186,
                            XCoord = 250,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 187,
                            XCoord = 300,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 188,
                            XCoord = 350,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 189,
                            XCoord = 400,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 190,
                            XCoord = 450,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 191,
                            XCoord = 500,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 192,
                            XCoord = 550,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 193,
                            XCoord = 600,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 194,
                            XCoord = 650,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 195,
                            XCoord = 700,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 196,
                            XCoord = 750,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 197,
                            XCoord = 800,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 198,
                            XCoord = 850,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 199,
                            XCoord = 900,
                            YCoord = 450
                        },
                        new
                        {
                            CityId = 200,
                            XCoord = 950,
                            YCoord = 450
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Database.Models.TravelPlan", b =>
                {
                    b.Property<int>("TravelPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureCityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("TravelPlanId");

                    b.ToTable("TravelPlans");

                    b.HasData(
                        new
                        {
                            TravelPlanId = 1,
                            Date = new DateTime(2020, 2, 8, 15, 16, 55, 379, DateTimeKind.Local).AddTicks(1908),
                            DepartureCityId = 1,
                            Description = "Migration Travel Plan",
                            DestinationCityId = 2,
                            IsActive = true,
                            SeatCount = 5
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Database.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Database.Models.UserTravelPlan", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TravelPlanId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUserOwner")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "TravelPlanId");

                    b.HasIndex("TravelPlanId");

                    b.ToTable("UserTravelPlan");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            TravelPlanId = 1,
                            IsUserOwner = true
                        });
                });

            modelBuilder.Entity("AdessoRideShare.Database.Models.UserTravelPlan", b =>
                {
                    b.HasOne("AdessoRideShare.Database.Models.TravelPlan", "TravelPlan")
                        .WithMany("UserTravelPlans")
                        .HasForeignKey("TravelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdessoRideShare.Database.Models.User", "User")
                        .WithMany("UserTravelPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
